// Mocks generated by Mockito 5.1.0 from annotations
// in myapp/test/widgets/register_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myapp/http/httpuser.dart' as _i2;
import 'package:myapp/model/user.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HttpConnectUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpConnectUser extends _i1.Mock implements _i2.HttpConnectUser {
  MockHttpConnectUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseurl =>
      (super.noSuchMethod(Invocation.getter(#baseurl), returnValue: '')
          as String);
  @override
  _i3.Future<bool> registerPost(_i4.User? user) =>
      (super.noSuchMethod(Invocation.method(#registerPost, [user]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> loginPosts(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#loginPosts, [username, password]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
